### ISSUE TITLE
position "up" in documentation

### ISSUE THREAD

**Issue by thleu-ethz-ch** [ghosh/microtip#43]
In the readme, the first example has `data-microtip-position="up"`. Took me some minutes to figure out that this is not a valid option. Please change it.

**Comment by ghosh** [comment]
@thleu-ethz-ch Thanks for pointing it out.

**Comment by robinmetral** [comment]
Can't believe how entitled some users of free, open-source libraries are

**Comment by serdar78** [comment]
Hello, I have a problem that I cannot solve, I cannot run the tooltip in scroll.for example, I have a scrolling navbar menu.when I hover over a menu name, the tooltip works fine on the right side. However, if I add scroll to the navbar, the tooltip is not displayed.it stays under the top div.I thought it was a Z-index problem but it didn't fix it.I would be very happy if you could help me.in short, the tooltip scroll does not work in a div or is there a problem with me?
 thank you

[here the tooltip works very well](https://ibb.co/SB7qcFB)
[But if I add scroll here it doesn't work it stays under div](https://ibb.co/F3n9DPg)
[because it stays under div](https://ibb.co/5nSQ7PN)
[burası html alanı](https://ibb.co/0jdgc2G)
